
package mancala;


public class MainBoard extends javax.swing.JFrame {

    /**
     * Creates new form MainBoard
     */
    private Mancala mancala;
    private Player playerOne;
    private Player playerTwo;
    
    
    public MainBoard() {
        initComponents();
        mancala = new Mancala();
        updateStonesForPlayerOne();
        updateStonesForPlayerTwo();
        
        
    }
    
    public void updateStonesForPlayerOne(){
        this.p1Slot0.setText("" + mancala.getPlayerOne().slots.get(0).countStones());
        this.p1Slot1.setText("" + mancala.getPlayerOne().slots.get(1).countStones());
        this.p1Slot2.setText("" + mancala.getPlayerOne().slots.get(2).countStones());
        this.p1Slot3.setText("" + mancala.getPlayerOne().slots.get(3).countStones());
        this.p1Slot4.setText("" + mancala.getPlayerOne().slots.get(4).countStones());
        this.p1Slot5.setText("" + mancala.getPlayerOne().slots.get(5).countStones());
        this.p1Slot6.setText("" + mancala.getPlayerOne().slots.get(6).countStones());
    }
    
    public void updateStonesForPlayerTwo(){
        this.p2Slot0.setText("" + mancala.getPlayerTwo().slots.get(0).countStones());
        this.p2Slot1.setText("" + mancala.getPlayerTwo().slots.get(1).countStones());
        this.p2Slot2.setText("" + mancala.getPlayerTwo().slots.get(2).countStones());
        this.p2Slot3.setText("" + mancala.getPlayerTwo().slots.get(3).countStones());
        this.p2Slot4.setText("" + mancala.getPlayerTwo().slots.get(4).countStones());
        this.p2Slot5.setText("" + mancala.getPlayerTwo().slots.get(5).countStones());
        this.p2Slot6.setText("" + mancala.getPlayerTwo().slots.get(6).countStones());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1Slot0 = new javax.swing.JLabel();
        p1Slot1 = new javax.swing.JLabel();
        p1Slot2 = new javax.swing.JLabel();
        p1Slot3 = new javax.swing.JLabel();
        p1Slot4 = new javax.swing.JLabel();
        p1Slot5 = new javax.swing.JLabel();
        p2Slot4 = new javax.swing.JLabel();
        p2Slot5 = new javax.swing.JLabel();
        p2Slot3 = new javax.swing.JLabel();
        p2Slot2 = new javax.swing.JLabel();
        p2Slot1 = new javax.swing.JLabel();
        p2Slot0 = new javax.swing.JLabel();
        p1Slot6 = new javax.swing.JLabel();
        p2Slot6 = new javax.swing.JLabel();
        playButton = new javax.swing.JButton();
        inputIndex = new javax.swing.JTextField();
        playButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        p1Slot0.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        p1Slot0.setText("jLabel1");

        p1Slot1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        p1Slot1.setText("jLabel1");

        p1Slot2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        p1Slot2.setText("jLabel1");

        p1Slot3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        p1Slot3.setText("jLabel1");

        p1Slot4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        p1Slot4.setText("jLabel1");

        p1Slot5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        p1Slot5.setText("jLabel1");

        p2Slot4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        p2Slot4.setText("jLabel1");

        p2Slot5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        p2Slot5.setText("jLabel1");

        p2Slot3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        p2Slot3.setText("jLabel1");

        p2Slot2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        p2Slot2.setText("jLabel1");

        p2Slot1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        p2Slot1.setText("jLabel1");

        p2Slot0.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        p2Slot0.setText("jLabel1");

        p1Slot6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        p1Slot6.setText("jLabel13");

        p2Slot6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        p2Slot6.setText("jLabel13");

        playButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        playButton.setText("Play (For PLayer 1)");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        inputIndex.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        playButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        playButton2.setText("Play (For Player 2)");
        playButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(inputIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(playButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p2Slot6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(p2Slot5)
                        .addGap(18, 18, 18)
                        .addComponent(p2Slot4)
                        .addGap(18, 18, 18)
                        .addComponent(p2Slot3)
                        .addGap(18, 18, 18)
                        .addComponent(p2Slot2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(p1Slot0)
                        .addGap(18, 18, 18)
                        .addComponent(p1Slot1)
                        .addGap(18, 18, 18)
                        .addComponent(p1Slot2)
                        .addGap(18, 18, 18)
                        .addComponent(p1Slot3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(p1Slot4)
                        .addGap(18, 18, 18)
                        .addComponent(p1Slot5)
                        .addGap(18, 18, 18)
                        .addComponent(p1Slot6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(p2Slot1)
                        .addGap(18, 18, 18)
                        .addComponent(p2Slot0)))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(p2Slot6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p1Slot0)
                            .addComponent(p1Slot1)
                            .addComponent(p1Slot2)
                            .addComponent(p1Slot3)
                            .addComponent(p1Slot4)
                            .addComponent(p1Slot5))
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p2Slot4)
                            .addComponent(p2Slot3)
                            .addComponent(p2Slot5)
                            .addComponent(p2Slot2)
                            .addComponent(p2Slot1)
                            .addComponent(p2Slot0))
                        .addGap(7, 7, 7)
                        .addComponent(p1Slot6, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playButton2))
                    .addComponent(inputIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        int index = Integer.parseInt(inputIndex.getText());
        mancala.getPlayerOne().moveStonesAround(index, mancala.getPlayerOne().slots.get(index));
        updateStonesForPlayerOne();
        updateStonesForPlayerTwo();
    }//GEN-LAST:event_playButtonActionPerformed

    private void playButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButton2ActionPerformed
        int index = Integer.parseInt(inputIndex.getText());
        mancala.getPlayerTwo().moveStonesAround(index, mancala.getPlayerTwo().slots.get(index));
        updateStonesForPlayerOne();
        updateStonesForPlayerTwo();
    }//GEN-LAST:event_playButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainBoard().setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputIndex;
    private javax.swing.JLabel p1Slot0;
    private javax.swing.JLabel p1Slot1;
    private javax.swing.JLabel p1Slot2;
    private javax.swing.JLabel p1Slot3;
    private javax.swing.JLabel p1Slot4;
    private javax.swing.JLabel p1Slot5;
    private javax.swing.JLabel p1Slot6;
    private javax.swing.JLabel p2Slot0;
    private javax.swing.JLabel p2Slot1;
    private javax.swing.JLabel p2Slot2;
    private javax.swing.JLabel p2Slot3;
    private javax.swing.JLabel p2Slot4;
    private javax.swing.JLabel p2Slot5;
    private javax.swing.JLabel p2Slot6;
    private javax.swing.JButton playButton;
    private javax.swing.JButton playButton2;
    // End of variables declaration//GEN-END:variables
}
